name: Bug Report
description: Report an incorrect calculation or unexpected behaviour
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproducible example
      description: A short code snippet that demonstrates the issue.
      render: typescript
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: 'e.g. 1.0.7'
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 'e.g. 20.11.0'
    validations:
      required: true
